config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  namespace :admin do
    root 'application#index'
    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
  end

  devise_for :users

  root 'projects#index'

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
  end

  resources :attachments, only: [:show, :new]

  namespace :api do
    resources :projects, only: [] do
      resources :tickets
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :project
  belongs_to :user, optional: true
  belongs_to :state

  has_many :tags_tickets, dependent: :destroy
  has_many :tags, through: :tags_tickets

  has_many :attachments, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_and_belongs_to_many :watchers, join_table: "ticket_watchers",
    class_name: "User", uniq: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank
  attr_accessor :tag_names

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }

  after_create :author_watches_me

  def tag_names=(names)
    @tag_names = names
    names.split.each do |name|
      self.tags << Tag.find_or_create_by(name: name)
    end
  end

  def author_watches_me
    if user.present? && !self.watchers.include?(user)
      self.watchers << user
    end
  end


end

app/controllers/api/tickets_controller.rb
class API::TicketsController < ApplicationController
  before_action :find_project, :authenticate_user

  attr_reader :current_user

  def show
    @ticket = @project.tickets.find(params[:id])
    authorize @ticket, :show?
    render json: @ticket
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def authenticate_user
    authenticate_with_http_token do |token|
      @current_user = User.find_by(api_key: token)
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :watch]

  def new
    @ticket = @project.tickets.build
    authorize @ticket, :create?
    @ticket.attachments.build
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.user = current_user

    authorize @ticket, :create?
    if @ticket.save
      flash[:success] = "Ticket was created successfully"
      redirect_to [@project, @ticket]
    else
      flash.now[:danger] = "Ticket has not been created"
      render :new
    end

  end

  def show
    authorize @ticket, :show?
    @comment = @ticket.comments.build(state_id: @ticket.state_id)
    respond_to do |format|
      format.html
      format.json { render json: @ticket }
    end
  end

  def watch
    authorize @ticket, :show?

    if @ticket.watchers.exists?(current_user)
      @ticket.watchers.destroy(current_user)
      flash[:notice] = "You are no longer watching this ticket."
    else
      @ticket.watchers << current_user
      flash[:notice] = "You are now watching this ticket."
    end

    redirect_to project_ticket_path(@ticket.project, @ticket)

  end

  def edit
    authorize @ticket, :update?
  end

  def update
    authorize @ticket, :update?

    if @ticket.update(ticket_params)
      flash[:success] = "Ticket was updated successfully"
      redirect_to [@project, @ticket]
    else
      flash.now[:danger] = "Error updating ticket"
      render :edit
    end
  end


  def destroy
    authorize @ticket, :destroy?

    @ticket.destroy
    flash[:success] = "Ticket was deleted successfully"
    redirect_to @project
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :description, :tag_names,
      attachments_attributes: [:file, :file_cache])
  end
end

app/helpers/api/tickets_helper.rb
module API::TicketsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper

  def toggle_watching_button(ticket)
    text = if ticket.watchers.include?(current_user)
      "Unwatch"
    else
      "Watch"
    end
    link_to text, watch_project_ticket_path(ticket.project, ticket),
      class: text.parameterize, method: :post
  end

end

app/views/tickets/_form.html.erb
<%= simple_form_for([project, ticket]) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :tag_names, label: "Tags" %>

  <div id="attachments">
    <h3>Attachments</h3>
    <%= render partial: "attachments/form", locals: { f: f, index: 0 } %>
  </div>

  <p>
    <%= link_to "Add another file", new_attachment_path, remote: true,
      id: "add_file", data: { params: {index: ticket.attachments.size} } %>
  </p>


  <%= f.button :submit, class: 'btn-primary' %>

<% end %>

app/views/tickets/edit.html.erb
<header>
  <h1>
    Edit ticket
  </h1>
  <h3><%= @project.name %></h3>
</header>

<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/new.html.erb
<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/show.html.erb
<div id="ticket">
  <header>
    <h1><%= @project.name %></h1>
  </header>

  <header>
    <h2><%= @ticket.name %></h2>

    <ul class="actions">
      <% if policy(@ticket).update? %>
        <li><%= link_to "Edit Ticket", [:edit, @project, @ticket],
          class: "edit" %></li>
      <% end %>

      <% if policy(@ticket).destroy? %>
        <li><%= link_to "Delete Ticket", [@project, @ticket], method: :delete, data: { confirm: "Are you sure you want to delete the ticket?" },
        class: "delete" %></li>
      <% end %>
    </ul>
  </header>
  <table id="attributes">
    <tr>
      <th>Author:</th>
      <td><%= @ticket.user.email %></td>
    </tr>
    <tr>
      <th>Created:</th>
      <td><%= time_ago_in_words(@ticket.created_at) %> ago</td>
    </tr>
    <% if @ticket.state.present? %>
      <tr>
        <th>State:</th>
        <td><%= render @ticket.state %></td>
      </tr>
    <% end %>
    <% if @ticket.tags.any? %>
      <tr id="tags">
        <th>Tags:</th>
        <td><%= render @ticket.tags %></td>
      </tr>
    <% end %>
    <tr id="watchers">
      <th>Watchers:</th>
      <td>
        <%= toggle_watching_button(@ticket) %><br />
        <%= @ticket.watchers.map(&:email).to_sentence %>
      </td>
    </tr>
  </table>




  <%= simple_format(@ticket.description) %>

  <% if @ticket.attachments.present? %>
    <h4>attachment</h4>
    <div class="attachments">
      <% @ticket.attachments.each do |attachment| %>
        <p>
          <%= link_to File.basename(attachment.file.url),
          attachment_path(attachment) %>
          (<%= number_to_human_size(attachment.file.size) %>)
        </p>
      <% end %>
    </div>
  <% end %>
</div>

<header>
  <h3>Comments</h3>
</header>

<div id="comments">
  <% if @ticket.comments.persisted.any? %>
    <%= render @ticket.comments.persisted %>
  <% else %>
    <p>There are no comments for this ticket.</p>
    <% end %>
</div>
<% if policy(@comment).create? %>
  <%= render "comments/form", ticket: @ticket, comment: @comment %>
<% end %>