config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  namespace :admin do
    root 'application#index'
    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
  end

  devise_for :users

  root 'projects#index'

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
  end

  resources :attachments, only: [:show, :new]

  namespace :api do
    resources :projects, only: [] do
      resources :tickets
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :name
  has_many :tickets, dependent: :delete_all
  has_many :roles, dependent: :delete_all


  def has_member?(user)
    roles.exists?(user_id: user)
  end

  [:manager, :editor, :viewer].each do |role|
    define_method "has_#{role}?" do |user|
      roles.exists?(user_id: user, role: role)
    end
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:success] = "Project has been created"
      redirect_to @project
    else
      flash.now[:danger] = "Project has not been created."
      render "new"
    end
  end

  def destroy
    @project = Project.find(params[:id])

    @project.destroy
    flash[:success] = "Project was deleted"
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = policy_scope(Project)
  end

  def show
    authorize @project, :show?
    @tickets = @project.tickets
    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def edit
    authorize @project, :update?
  end


  def update
    authorize @project, :update?
    if @project.update(project_params)
      flash[:success] = "Project was updated successfully"
      redirect_to @project
    else
      flash.now[:danger] = "Error updating the project"
      render :edit
    end
  end


  private

  def find_project
    @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:danger] = "The project you are looking for could not be found"
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(project) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h2>Edit project</h2>
</div>

<div class="col-md-6 col-md-offset-3">
  <%= render 'form', project: @project %>
</div>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>Projects</h1>
  <ul class="actions">
    <% admins_only do %>
      <li><%= link_to "New Project", new_admin_project_path,
      class: "new" %></li>
    <% end %>
  </ul>
</div>


<div id="projects">
  <% @projects.each do |project| %>
    <div class="project">
      <h2><%= link_to project.name, project %></h2>
      <p><%= project.description %></p>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<% provide(:title, "Projects - Ticketee") %>

<div class="page-header">
  <h1><%= @project.name %></h1>

  <ul class="actions">

    <% if policy(Ticket.new(project: @project)).create? %>
      <li><%= link_to "New Ticket", new_project_ticket_path(@project),
        class: "new" %>
      </li>
    <% end %>
    <% if policy(@project).update? %>
      <li><%= link_to "Edit Project",
      edit_project_path(@project), class: "edit" %></li>
    <% end %>
    <% admins_only do %>
      <li>
        <%= link_to "Delete Project",
      admin_project_path(@project),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this project?" },
      class: "delete" %>
      </li>
    <% end %>
  </ul>
</div>

<p><%= @project.description %></p>

<ul id="tickets">
  <% @tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> -
      <%= link_to ticket.name, [@project, ticket] %>
      <%= render ticket.state if ticket.state %>
    </li>
  <% end %>
</ul>